version: "3.9"

services:
  db:
    image: postgres:15.1-alpine3.17
    container_name: app-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=app_db
    ports:
      - 5432:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data